### PR TITLE
GeoCoding Support

### PR DESCRIPTION
**Pull request by DerekTBrown**
This is still a work in progress, but I need some way to be able to collaborate on getting this to work.  I modified an existing GEM to accept OpenMapquest API Keys, so that it can convert location strings into machine-readable data.  I have done this in the past by iterating through the entire MySQL Dump, but as the dataset gets bigger and bigger, that has become nearly impossible, so I would like to add realtime support for this operation.

### CODE REVIEW

**Comment by DerekTBrown** [comment]
@gousiosg - This is a somewhat complex project, and I am not sure what other things I have to change to make this work (MySQL Schemas etc).  Any advice you could give would be awesome.

**Comment by gousiosg** [comment]
There are few things missing before merge:

* A db migration to add the required fields in the user table. See `lib/ghtorrent/migrations`
* A process to do this for existing users. You might want to extend the `lib/ghtorrent/commands/full_user_retriever.rb` script
* To make this work in the live collection, you need to ensure that the API you are querying can support around 5k queries an hour.

**Comment by DerekTBrown** [comment]
Okay @gousiosg, I added a simple migration to add the columns to the database.

I think it would be best to get this part running before geocoding the existing users for two reasons 1) because I am not sure it can handle the massive volume of trying to do all the users at once and 2) handling this in an external process (and not an internal ruby file) will be safer and more efficient.

**Comment by gousiosg** [comment]
This is redundant now

**Pull request closed without merging**
