### PR TITLE
Added missing column and missing table

### PR DESCRIPTION
**Pull request by sbaltes**
1. Added missing column "updated_at" to table "projects" (not sure about the default value here)

2. Added missing table "project_languages" (not sure about the primary key here)

### CODE REVIEW

**Comment by gousiosg** [comment]
@sbaltes, thanks once again for fixing those issues. You can find details about the missing primary key/defaults by examining the DB migrations here:

https://github.com/gousiosg/github-mirror/tree/master/lib/ghtorrent/migrations

**Comment by sbaltes** [comment]
Thanks for the info. I have some comments/questions:

Regarding the default value of "updated_at":
In the schema file, the SQL mode is set to TRADITIONAL, which, at least in my version of MySQL, activates NO_ZERO_DATE (see http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_traditional). Therefore, setting a default value of 0 is not possible for this column. My workaround was to set the oldest value possible.

Regarding the primary key of table "project_languages":
I'm not an SQL expert, but is it okay to only have a foreign key constraint but no primary key for that table? If multiple languages per project are possible, then one could set the foreign key constraint and make (project_id, language) the primary key.

**Comment by gousiosg** [comment]
I am not sure. Here is what MySQL reports as creation command for this table. It should be enough I guess

```sql
 project_languages | CREATE TABLE `project_languages` (
  `project_id` int(11) NOT NULL,
  `language` varchar(255) NOT NULL,
  `bytes` int(11) NOT NULL DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `project_id` (`project_id`),
  CONSTRAINT `project_languages_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by sbaltes** [comment]
Okay, I added the missing index for column `project_id`. Table `project_languages` should now be fine. I also committed my workaround for the default value of column `updated_at` in table `projects`. You can decide if you want to merge this or change the `SQL_MODE` such that a default value of 0 is possible (http://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html).

**Comment by sbaltes** [comment]
Maybe it would also be a good idea to create an index for each foreign key defined in the schema. Of course it's a trade-off between the space for the index and improved look-up times.

**Comment by gousiosg** [comment]
MySQL does this by default I think.

**Comment by sbaltes** [comment]
Your are right: 

> "MySQL requires indexes on foreign keys and referenced keys so that foreign key checks can be fast and not require a table scan. In the referencing table, there must be an index where the foreign key columns are listed as the first columns in the same order. Such an index is created on the referencing table automatically if it does not exist. This index might be silently dropped later, if you create another index that can be used to enforce the foreign key constraint." 

https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html

**Pull request merged**
