### PR TITLE
DB Migration scripts

### PR DESCRIPTION
**Pull request by PDegenPortnoy**
This is to help use review the scripts to migrate from MySQL to PostgreSQL. Ultimately, this (in its final, approved form) will be merged to the blackducksoftware/github-mirror master, which will update the PR opened against the gousiosg/github-mirror master

### CODE REVIEW

**Comment by gousiosg** [comment]
Hi, thanks! 

In general, the contents of this PR do not need to be in the repo, as they are an one-off migration step.

So I 've tried following the instructions in the included `doc/db_migration_script/README.md` file. I installed Postgres on my servers, installed `pgloader`, run the timestamp updates (also fixed them on the main MySQL server) etc. At the moment, it looks like its working.

**Comment by gousiosg** [comment]
It looks like that something is wrong with inserting data into postgres.

```
2018-09-13T15:49:59.098000+02:00 DEBUG Reader started for public.issue_comments
2018-09-13T15:49:59.098000+02:00 DEBUG start public.issue_comments   111105
2018-09-13T15:49:59.098000+02:00 DEBUG Finished processing WRITER for "public.commit_comments"  104.080000s
2018-09-13T15:49:59.099000+02:00 DEBUG writers-counts[public.commit_comments] = 0
2018-09-13T15:49:59.100000+02:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://ght@127.0.0.1:3306/ghtorrent {1009CEE6E3}>
2018-09-13T15:49:59.100000+02:00 SQL MySQL: sending query: set net_read_timeout = 120;
2018-09-13T15:49:59.100000+02:00 SQL MySQL: sending query: set net_write_timeout = 240;
2018-09-13T15:49:59.100000+02:00 SQL MySQL: sending query: SELECT `issue_id`, `user_id`, `comment_id`, `created_at` FROM `issue_comments`
2018-09-13T15:57:40.869000+02:00 DEBUG Reader for public.issue_comments is done in 461.770000s
2018-09-13T15:57:40.869000+02:00 DEBUG Reader started for public.issue_labels
2018-09-13T15:57:40.869000+02:00 DEBUG start public.issue_labels   572876
2018-09-13T15:57:40.869000+02:00 DEBUG Finished processing READER for "public.issue_comments"  461.770000s
2018-09-13T15:57:40.871000+02:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://ght@127.0.0.1:3306/ghtorrent {1009CEE763}>
2018-09-13T15:57:40.871000+02:00 SQL MySQL: sending query: set net_read_timeout = 120;
2018-09-13T15:57:40.871000+02:00 SQL MySQL: sending query: set net_write_timeout = 240;
2018-09-13T15:57:40.872000+02:00 SQL MySQL: sending query: SELECT `label_id`, `issue_id` FROM `issue_labels`
2018-09-13T15:57:40.914000+02:00 SQL ALTER TABLE issue_comments ENABLE TRIGGER ALL;
2018-09-13T15:57:40.915000+02:00 DEBUG  stop public.issue_comments   | 111105 .. 572922 = 461.817d0
2018-09-13T15:57:40.915000+02:00 DEBUG Writer[0] for public.issue_comments is done in 343.208000s
2018-09-13T15:57:40.915000+02:00 DEBUG Finished processing WRITER for "public.issue_comments"  343.208000s
2018-09-13T15:57:40.915000+02:00 DEBUG writers-counts[public.issue_comments] = 0
2018-09-13T15:57:40.915000+02:00 INFO COPY ON ERROR STOP
2018-09-13T15:57:40.919000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://ghtorrent@127.0.0.1:5432/ghtorrent {1029F90323}>
2018-09-13T15:57:40.919000+02:00 DEBUG SET client_encoding TO 'utf8'
2018-09-13T15:57:40.919000+02:00 DEBUG SET maintenance_work_mem TO '128MB'
2018-09-13T15:57:40.919000+02:00 DEBUG SET work_mem TO '12MB'
2018-09-13T15:57:40.919000+02:00 DEBUG SET application_name TO 'pgloader'
2018-09-13T15:57:40.920000+02:00 SQL SET search_path TO public;
2018-09-13T15:57:40.920000+02:00 SQL ALTER TABLE issue_labels DISABLE TRIGGER ALL;
2018-09-13T15:57:40.920000+02:00 INFO pgsql:copy-rows-from-queue[0]: public.issue_labels (label_id issue_id)
2018-09-13T15:58:26.465000+02:00 DEBUG Reader for public.issue_labels is done in 45.596000s
2018-09-13T15:58:26.465000+02:00 DEBUG Reader started for public.projects
2018-09-13T15:58:26.465000+02:00 DEBUG Finished processing READER for "public.issue_labels"  45.596000s
2018-09-13T15:58:26.465000+02:00 DEBUG start public.projects   618472
2018-09-13T15:58:26.467000+02:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://ght@127.0.0.1:3306/ghtorrent {1009CEE7C3}>
2018-09-13T15:58:26.467000+02:00 SQL MySQL: sending query: set net_read_timeout = 120;
2018-09-13T15:58:26.467000+02:00 SQL MySQL: sending query: set net_write_timeout = 240;
2018-09-13T15:58:26.467000+02:00 SQL MySQL: sending query: SELECT `id`, `url`, `owner_id`, `name`, `description`, `language`, `created_at`, `forked_from`, `deleted`, `updated_at` FROM `projects`
2018-09-13T15:58:26.514000+02:00 SQL ALTER TABLE issue_labels ENABLE TRIGGER ALL;
2018-09-13T15:58:26.515000+02:00 DEBUG  stop public.issue_labels   | 572876 .. 618522 = 45.646d0
2018-09-13T15:58:26.515000+02:00 DEBUG Writer[0] for public.issue_labels is done in 22.196000s
2018-09-13T15:58:26.515000+02:00 DEBUG Finished processing WRITER for "public.issue_labels"  22.196000s
2018-09-13T15:58:26.516000+02:00 DEBUG writers-counts[public.issue_labels] = 0
```

**Comment by PDegenPortnoy** [comment]
@Priya5 Can you please review the comments?

**Comment by Priya5** [comment]
> It looks like that something is wrong with inserting data into postgres.
> 
> ```
> 2018-09-13T15:49:59.098000+02:00 DEBUG Reader started for public.issue_comments
> 2018-09-13T15:49:59.098000+02:00 DEBUG start public.issue_comments   111105
> 2018-09-13T15:49:59.098000+02:00 DEBUG Finished processing WRITER for "public.commit_comments"  104.080000s
> 2018-09-13T15:49:59.099000+02:00 DEBUG writers-counts[public.commit_comments] = 0
> 2018-09-13T15:49:59.100000+02:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://ght@127.0.0.1:3306/ghtorrent {1009CEE6E3}>
> 2018-09-13T15:49:59.100000+02:00 SQL MySQL: sending query: set net_read_timeout = 120;
> 2018-09-13T15:49:59.100000+02:00 SQL MySQL: sending query: set net_write_timeout = 240;
> 2018-09-13T15:49:59.100000+02:00 SQL MySQL: sending query: SELECT `issue_id`, `user_id`, `comment_id`, `created_at` FROM `issue_comments`
> 2018-09-13T15:57:40.869000+02:00 DEBUG Reader for public.issue_comments is done in 461.770000s
> 2018-09-13T15:57:40.869000+02:00 DEBUG Reader started for public.issue_labels
> 2018-09-13T15:57:40.869000+02:00 DEBUG start public.issue_labels   572876
> 2018-09-13T15:57:40.869000+02:00 DEBUG Finished processing READER for "public.issue_comments"  461.770000s
> 2018-09-13T15:57:40.871000+02:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://ght@127.0.0.1:3306/ghtorrent {1009CEE763}>
> 2018-09-13T15:57:40.871000+02:00 SQL MySQL: sending query: set net_read_timeout = 120;
> 2018-09-13T15:57:40.871000+02:00 SQL MySQL: sending query: set net_write_timeout = 240;
> 2018-09-13T15:57:40.872000+02:00 SQL MySQL: sending query: SELECT `label_id`, `issue_id` FROM `issue_labels`
> 2018-09-13T15:57:40.914000+02:00 SQL ALTER TABLE issue_comments ENABLE TRIGGER ALL;
> 2018-09-13T15:57:40.915000+02:00 DEBUG  stop public.issue_comments   | 111105 .. 572922 = 461.817d0
> 2018-09-13T15:57:40.915000+02:00 DEBUG Writer[0] for public.issue_comments is done in 343.208000s
> 2018-09-13T15:57:40.915000+02:00 DEBUG Finished processing WRITER for "public.issue_comments"  343.208000s
> 2018-09-13T15:57:40.915000+02:00 DEBUG writers-counts[public.issue_comments] = 0
> 2018-09-13T15:57:40.915000+02:00 INFO COPY ON ERROR STOP
> 2018-09-13T15:57:40.919000+02:00 DEBUG CONNECTED TO #<PGLOADER.PGSQL:PGSQL-CONNECTION pgsql://ghtorrent@127.0.0.1:5432/ghtorrent {1029F90323}>
> 2018-09-13T15:57:40.919000+02:00 DEBUG SET client_encoding TO 'utf8'
> 2018-09-13T15:57:40.919000+02:00 DEBUG SET maintenance_work_mem TO '128MB'
> 2018-09-13T15:57:40.919000+02:00 DEBUG SET work_mem TO '12MB'
> 2018-09-13T15:57:40.919000+02:00 DEBUG SET application_name TO 'pgloader'
> 2018-09-13T15:57:40.920000+02:00 SQL SET search_path TO public;
> 2018-09-13T15:57:40.920000+02:00 SQL ALTER TABLE issue_labels DISABLE TRIGGER ALL;
> 2018-09-13T15:57:40.920000+02:00 INFO pgsql:copy-rows-from-queue[0]: public.issue_labels (label_id issue_id)
> 2018-09-13T15:58:26.465000+02:00 DEBUG Reader for public.issue_labels is done in 45.596000s
> 2018-09-13T15:58:26.465000+02:00 DEBUG Reader started for public.projects
> 2018-09-13T15:58:26.465000+02:00 DEBUG Finished processing READER for "public.issue_labels"  45.596000s
> 2018-09-13T15:58:26.465000+02:00 DEBUG start public.projects   618472
> 2018-09-13T15:58:26.467000+02:00 DEBUG CONNECTED TO #<MYSQL-CONNECTION mysql://ght@127.0.0.1:3306/ghtorrent {1009CEE7C3}>
> 2018-09-13T15:58:26.467000+02:00 SQL MySQL: sending query: set net_read_timeout = 120;
> 2018-09-13T15:58:26.467000+02:00 SQL MySQL: sending query: set net_write_timeout = 240;
> 2018-09-13T15:58:26.467000+02:00 SQL MySQL: sending query: SELECT `id`, `url`, `owner_id`, `name`, `description`, `language`, `created_at`, `forked_from`, `deleted`, `updated_at` FROM `projects`
> 2018-09-13T15:58:26.514000+02:00 SQL ALTER TABLE issue_labels ENABLE TRIGGER ALL;
> 2018-09-13T15:58:26.515000+02:00 DEBUG  stop public.issue_labels   | 572876 .. 618522 = 45.646d0
> 2018-09-13T15:58:26.515000+02:00 DEBUG Writer[0] for public.issue_labels is done in 22.196000s
> 2018-09-13T15:58:26.515000+02:00 DEBUG Finished processing WRITER for "public.issue_labels"  22.196000s
> 2018-09-13T15:58:26.516000+02:00 DEBUG writers-counts[public.issue_labels] = 0
> ```

This is how the pgloader displays debug level information at the console.

It seems like data.load script is not executed completely and that is why some tables are empty.
On successful completion of scripts, it should log the summary at the console like below:
```
2018-08-06T16:11:39.711000Z NOTICE Completing PostgreSQL database.
2018-08-06T16:11:39.713000Z NOTICE Reset sequences
2018-08-06T17:13:21.713000Z LOG report summary reset
                  table name     errors       read   imported      bytes      total time       read      write
----------------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
             fetch meta data          0         20         20                     0.074s
----------------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
      public.commit_comments          0    4969882    4969882   841.2 MB       4m29.111s  4m25.648s  2m40.015s
       public.commit_parents          0  1023029071  1023029071    19.0 GB     1h52m4.288s  1h52m4.004s  53m43.145s
       public.issue_comments          0  117107749  117107749     5.0 GB      43m28.853s  43m26.836s  25m21.929s
            public.followers          0   27365808   27365808   926.5 MB       9m50.661s  9m50.574s  5m32.169s
         public.issue_events          0  103775100  103775100     6.1 GB       41m7.653s  41m6.765s  31m14.052s
         public.issue_labels          0   21094804   21094804   351.3 MB       5m51.949s  5m51.877s  1m32.145s
             public.projects          0   92648496   92648496    15.1 GB    1h27m29.815s  1h27m26.616s  55m47.908s
 public.organization_members          0     625158     625158    21.1 MB         21.848s    13.745s     7.513s
    public.project_languages          0  110477692  110477692     4.2 GB      45m23.883s  45m23.823s  17m3.615s
       public.project_topics          0      71148      71148     2.8 MB          2.707s     2.647s     0.486s
public.pull_request_comments          0   24895544   24895544     3.8 GB      23m32.836s  23m29.103s  13m34.907s
 public.pull_request_history          0   96423894   96423894     4.7 GB       44m8.121s  44m8.055s  19m12.168s
      public.project_members          0   10906928   10906928   518.2 MB       4m15.515s  4m15.215s   3m8.584s
        public.pull_requests          0   37597361   37597361     1.8 GB      19m48.725s  19m48.651s   5m9.128s
 public.pull_request_commits          0  190484002  190484002     3.3 GB      32m49.934s  32m49.900s  11m26.501s
      public.repo_milestones          0          0          0                     0.196s     0.192s
                public.users          0   25965747   25965747     2.0 GB      14m59.302s  14m59.189s  8m14.602s
          public.repo_labels          0  283535108  283535108     7.3 GB      39m15.954s  39m15.905s  25m8.242s
          public.schema_info          0          0          0                     0.004s     0.002s
             public.watchers          0  112204725  112204725     3.8 GB      16m34.106s  16m34.018s  10m20.380s
----------------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
     COPY Threads Completion          0          4          4                6h1m33.107s
             Reset Sequences          0          7          7                1h1m41.757s
            Install Comments          0          0          0                     0.000s
----------------------------  ---------  ---------  ---------  ---------  --------------  ---------  ---------
           Total import time          ✓  2283178217  2283178217    78.7 GB     7h3m14.865s

```

Please share the /tmp/pgloader/pgloader.log file. This log file will help in analyzing if anything is wrong.

**Comment by Priya5** [comment]
> And here is the equivalent query in the source MySQL. It looks like some rows are missing as well.
> 
> ```sql
> mysql> SELECT TABLE_NAME,SUM(TABLE_ROWS)   
> FROM INFORMATION_SCHEMA.TABLES   
> WHERE TABLE_SCHEMA = 'ghtorrent'  
> GROUP BY TABLE_NAME;
> +-----------------------+-----------------+
> | TABLE_NAME            | SUM(TABLE_ROWS) |
> +-----------------------+-----------------+
> | commits               |       847317157 |
> | commit_comments       |         4526360 |
> | commit_parents        |       849437631 |
> | followers             |        16706808 |
> | issues                |        61424031 |
> | issue_comments        |        99676228 |
> | issue_events          |        86893427 |
> | issue_labels          |        17882408 |
> | organization_members  |          462655 |
> | projects              |        74848130 |
> | project_commits       |      5417294109 |
> | project_languages     |       108873209 |
> | project_members       |         9910250 |
> | project_topics        |           12856 |
> | pull_requests         |        30665111 |
> | pull_request_comments |        19994246 |
> | pull_request_commits  |       154628416 |
> | pull_request_history  |        77573149 |
> | repo_labels           |       277523803 |
> | repo_milestones       |               0 |
> | schema_info           |               0 |
> | users                 |        22150184 |
> | watchers              |        92460619 |
> +-----------------------+-----------------+
> 23 rows in set (0.00 sec)
> ```

There are two cases here.
1. If we go via INFORMATION_SCHEMA query then it gets executed quickly but gives an approximate record count. 
2. If we go via select count(*) from table_name query then it gives 100% accurate result at the cost of some execution time.

So please share the exact count of records from mysql and postgres by following the 2nd approach as mentioned above.

**Comment by gousiosg** [comment]
We will use the migration process described in #75 to do the migration. Thanks anyway!

**Pull request closed without merging**
